version: '3.8'

services:
  ego-net-backend:
    build: ./backend
    ports: 
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: unless-stopped
    
  ego-net-frontend:
    build: ./frontend
    ports: 
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - ego-net-backend
    restart: unless-stopped